name: generate-brd
description: |
  Generate a Business Requirements Document (BRD) for a software feature.
  Uses code graph and filesystem to understand the codebase context.

# Trigger patterns - Copilot SDK matches these to activate skill
triggers:
  - "generate brd"
  - "create brd"
  - "write brd"
  - "business requirements"
  - "generate requirements document"
  - "create requirements"

# MCP servers this skill needs access to
mcp_servers:
  - neo4j-code-graph    # For querying code structure, dependencies
  - filesystem          # For reading source files

# Tools available to the skill (from the MCP servers)
tools:
  # Neo4j MCP tools (actual tool names from @neo4j-contrib/mcp-neo4j)
  - name: get-neo4j-schema
    description: Get the Neo4j database schema to understand available node types and relationships
  - name: read-neo4j-cypher
    description: Execute read-only Cypher queries on the code graph to find components, classes, functions

  # Filesystem MCP tools (actual tool names from @modelcontextprotocol/server-filesystem)
  - name: read_file
    description: Read source code files
  - name: list_directory
    description: List files in a directory
  - name: search_files
    description: Search for files matching a pattern
  - name: get_file_info
    description: Get metadata about a file

# Instructions for the LLM when this skill is activated
instructions: |
  You are generating a Business Requirements Document (BRD) for a software feature.

  ## Process

  1. **Get the Schema First**
     - ALWAYS call `get-neo4j-schema` first to understand available node types
     - This prevents hallucinating non-existent labels or relationships

  2. **Discover Components** (USE THE TOOLS!)
     - Use `read-neo4j-cypher` with case-insensitive search:
       ```cypher
       MATCH (n) WHERE toLower(n.name) CONTAINS toLower('keyword')
       RETURN labels(n) as type, n.name as name, n.filePath as file LIMIT 20
       ```
     - DO NOT ask user for component names - discover them yourself!
     - Iterate: start broad, then drill down into specific components

  3. **Read Source Files**
     - Use filesystem tools to read actual source code
     - Understand existing patterns and conventions

  4. **Generate the BRD**
     - Follow the template structure provided
     - Reference actual code components discovered
     - Include specific file paths and class names
     - Make claims that can be verified against the codebase

  ## Important Guidelines

  - ALWAYS call `get-neo4j-schema` first
  - Use `toLower()` with `CONTAINS` for flexible matching
  - DO NOT ask for affected_components - discover them!
  - Reference actual component names and file paths
  - Be specific and verifiable in all claims

  ## Output Format

  Generate the BRD in Markdown format following the provided template structure.
