name: generate-epics
description: |
  Generate Epics from an approved BRD document.
  Breaks down requirements into implementation epics with dependencies.

# Trigger patterns
triggers:
  - "generate epics"
  - "create epics"
  - "break down brd"
  - "epic breakdown"
  - "create epic from brd"

# MCP servers needed
mcp_servers:
  - neo4j-code-graph
  - filesystem

# Tools available (actual MCP tool names)
tools:
  # Neo4j MCP tools
  - name: get-neo4j-schema
    description: Get the database schema to understand available node types
  - name: read-neo4j-cypher
    description: Find components and their dependencies to understand scope

  # Filesystem MCP tools
  - name: read_file
    description: Read code to understand implementation complexity
  - name: list_directory
    description: Explore project structure

# Instructions
instructions: |
  You are generating Epics from an approved BRD document.

  ## Process

  1. **Get Schema First**
     - Call `get-neo4j-schema` to understand available node types

  2. **Analyze the BRD**
     - Extract functional and technical requirements
     - Identify major feature areas

  3. **Query the Codebase** (USE THE TOOLS!)
     - Use `read-neo4j-cypher` to find existing components:
       ```cypher
       MATCH (n) WHERE toLower(n.name) CONTAINS toLower('keyword')
       RETURN labels(n) as type, n.name as name, n.filePath as file
       ```
     - Find dependencies between components
     - Assess complexity by reading relevant code

  4. **Generate Epics**
     For each major feature area, create an Epic with:
     - Title and description
     - Affected components (from code graph)
     - Dependencies (blocked_by, blocks)
     - Estimated effort (small/medium/large)
     - Priority

  ## Output Format

  ```json
  {
    "epics": [
      {
        "id": "EPIC-001",
        "title": "Implement Order Processing Pipeline",
        "description": "...",
        "components": ["OrderService", "PaymentGateway"],
        "priority": "high",
        "estimated_effort": "large",
        "blocked_by": [],
        "blocks": ["EPIC-002"]
      }
    ],
    "implementation_order": ["EPIC-001", "EPIC-002", "EPIC-003"]
  }
  ```
